#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Oct 16 21:56:33 CEST 2022
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim red_pitaya_top_behav -key {Behavioral:sim_1:Functional:red_pitaya_top} -tclbatch red_pitaya_top.tcl -protoinst "protoinst_files/system.protoinst" -log simulate.log"
xsim red_pitaya_top_behav -key {Behavioral:sim_1:Functional:red_pitaya_top} -tclbatch red_pitaya_top.tcl -protoinst "protoinst_files/system.protoinst" -log simulate.log

