# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/classic/sdc/red_pitaya.xdc

# XDC: imports/classic/prj/classic/sdc/red_pitaya.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0 || ORIG_REF_NAME==system_proc_sys_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0/system_processing_system7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0 || ORIG_REF_NAME==system_processing_system7_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0/system_xlconstant_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0 || ORIG_REF_NAME==system_xlconstant_0} -quiet] -quiet

# IP: bd/system/ip/system_rp_expansion_to_in_0_0/system_rp_expansion_to_in_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rp_expansion_to_in_0_0 || ORIG_REF_NAME==system_rp_expansion_to_in_0_0} -quiet] -quiet

# IP: bd/system/ip/system_acquire_top_0_2/system_acquire_top_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_acquire_top_0_2 || ORIG_REF_NAME==system_acquire_top_0_2} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
