# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/bd/system/ip/system_reg_ctrl_top_0_0/system_reg_ctrl_top_0_0.xci
# IP: The module: 'system_reg_ctrl_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/ip/reg_ctrl/reg_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==reg_ctrl || ORIG_REF_NAME==reg_ctrl} -quiet] -quiet

# XDC: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/bd/system/ip/system_reg_ctrl_top_0_0/system_reg_ctrl_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_reg_ctrl_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/bd/system/ip/system_reg_ctrl_top_0_0/system_reg_ctrl_top_0_0.xci
# IP: The module: 'system_reg_ctrl_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/ip/reg_ctrl/reg_ctrl.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==reg_ctrl || ORIG_REF_NAME==reg_ctrl} -quiet] -quiet

# XDC: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/bd/system/ip/system_reg_ctrl_top_0_0/system_reg_ctrl_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_reg_ctrl_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
