# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/classic/sdc/red_pitaya.xdc

# XDC: imports/classic/prj/stream_app/sdc/red_pitaya.xdc

# IP: ip/fifo_axi_data/fifo_axi_data.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] -quiet

# IP: ip/fifo_axi_req/fifo_axi_req.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] -quiet

# IP: ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_2/system_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_2 || ORIG_REF_NAME==system_xbar_2} -quiet] -quiet

# IP: bd/system/ip/system_axi_reg_0/system_axi_reg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_reg_0 || ORIG_REF_NAME==system_axi_reg_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_gen_0/system_clk_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_gen_0 || ORIG_REF_NAME==system_clk_gen_0} -quiet] -quiet

# IP: bd/system/ip/system_intr_concat_0/system_intr_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_intr_concat_0 || ORIG_REF_NAME==system_intr_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rp_concat_0/system_rp_concat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rp_concat_0 || ORIG_REF_NAME==system_rp_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_rp_dac_0/system_rp_dac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rp_dac_0 || ORIG_REF_NAME==system_rp_dac_0} -quiet] -quiet

# IP: bd/system/ip/system_rp_oscilloscope_0/system_rp_oscilloscope_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rp_oscilloscope_0 || ORIG_REF_NAME==system_rp_oscilloscope_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_gen_0/system_rst_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_gen_0 || ORIG_REF_NAME==system_rst_gen_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_gen2_0/system_rst_gen2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_gen2_0 || ORIG_REF_NAME==system_rst_gen2_0} -quiet] -quiet

# IP: bd/system/ip/system_xadc_0/system_xadc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_0 || ORIG_REF_NAME==system_xadc_0} -quiet] -quiet

# IP: bd/system/ip/system_rp_counter_0_0/system_rp_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rp_counter_0_0 || ORIG_REF_NAME==system_rp_counter_0_0} -quiet] -quiet

# IP: ip/fifo_axi_data/fifo_axi_data.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] -quiet

# IP: ip/fifo_axi_req/fifo_axi_req.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] -quiet

# IP: ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_1_0/system_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_1_0 || ORIG_REF_NAME==system_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/system/ip/system_rp_expansion_to_in_0_0/system_rp_expansion_to_in_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rp_expansion_to_in_0_0 || ORIG_REF_NAME==system_rp_expansion_to_in_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_1/system_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_2/system_auto_cc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_2 || ORIG_REF_NAME==system_auto_cc_2} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_2/system_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_2 || ORIG_REF_NAME==system_auto_pc_2} -quiet] -quiet

# XDC: ip/fifo_axi_data/fifo_axi_data.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_axi_data/fifo_axi_data_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_axi_req/fifo_axi_req.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_axi_req/fifo_axi_req_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_axi_data/fifo_axi_data.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_axi_data/fifo_axi_data_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_axi_req/fifo_axi_req.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/fifo_axi_req/fifo_axi_req_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
