# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rst_gen2_0/system_rst_gen2_0.xci
# IP: The module: 'system_rst_gen2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rst_gen2_0/system_rst_gen2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_gen2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rst_gen2_0/system_rst_gen2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_gen2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rst_gen2_0/system_rst_gen2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_gen2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rst_gen2_0/system_rst_gen2_0.xci
# IP: The module: 'system_rst_gen2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rst_gen2_0/system_rst_gen2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_gen2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rst_gen2_0/system_rst_gen2_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_gen2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rst_gen2_0/system_rst_gen2_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rst_gen2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
