# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/classic/sdc/red_pitaya.xdc

# XDC: imports/classic/prj/classic/sdc/red_pitaya.xdc

# IP: ip/FIFO_16_64/FIFO_16_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_16_64 || ORIG_REF_NAME==FIFO_16_64} -quiet] -quiet

# IP: ip/reg_ctrl/reg_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==reg_ctrl || ORIG_REF_NAME==reg_ctrl} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_proc_sys_reset_0/system_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_proc_sys_reset_0 || ORIG_REF_NAME==system_proc_sys_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0/system_processing_system7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_processing_system7_0 || ORIG_REF_NAME==system_processing_system7_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0/system_xlconstant_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0 || ORIG_REF_NAME==system_xlconstant_0} -quiet] -quiet

# IP: bd/system/ip/system_rp_expansion_to_in_0_0/system_rp_expansion_to_in_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rp_expansion_to_in_0_0 || ORIG_REF_NAME==system_rp_expansion_to_in_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_0_0/system_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_0_0 || ORIG_REF_NAME==system_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_HP_top_0_0/system_AXI_HP_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_HP_top_0_0 || ORIG_REF_NAME==system_AXI_HP_top_0_0} -quiet] -quiet

# IP: ip/FIFO_16_64/FIFO_16_64.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_16_64 || ORIG_REF_NAME==FIFO_16_64} -quiet] -quiet

# IP: bd/system/ip/system_reg_ctrl_top_0_0/system_reg_ctrl_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_reg_ctrl_top_0_0 || ORIG_REF_NAME==system_reg_ctrl_top_0_0} -quiet] -quiet

# IP: ip/reg_ctrl/reg_ctrl.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==reg_ctrl || ORIG_REF_NAME==reg_ctrl} -quiet] -quiet

# IP: bd/system/ip/system_acquire_top_0_4/system_acquire_top_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_acquire_top_0_4 || ORIG_REF_NAME==system_acquire_top_0_4} -quiet] -quiet

# IP: bd/system/ip/system_axi_interconnect_1_0/system_axi_interconnect_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_interconnect_1_0 || ORIG_REF_NAME==system_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/system/ip/system_waveform_top_0_0/system_waveform_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_waveform_top_0_0 || ORIG_REF_NAME==system_waveform_top_0_0} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# IP: bd/system/ip/system_generate_top_0_0/system_generate_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_generate_top_0_0 || ORIG_REF_NAME==system_generate_top_0_0} -quiet] -quiet

# IP: bd/system/ip/system_integrator_top_0_0/system_integrator_top_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_integrator_top_0_0 || ORIG_REF_NAME==system_integrator_top_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_0/system_auto_cc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_0 || ORIG_REF_NAME==system_auto_cc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_cc_1/system_auto_cc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_cc_1 || ORIG_REF_NAME==system_auto_cc_1} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_1/system_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_1 || ORIG_REF_NAME==system_auto_pc_1} -quiet] -quiet

# XDC: ip/FIFO_16_64/FIFO_16_64.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16_64 || ORIG_REF_NAME==FIFO_16_64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/FIFO_16_64/FIFO_16_64_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16_64 || ORIG_REF_NAME==FIFO_16_64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: ip/FIFO_16_64/FIFO_16_64.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16_64 || ORIG_REF_NAME==FIFO_16_64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/FIFO_16_64/FIFO_16_64_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_16_64 || ORIG_REF_NAME==FIFO_16_64} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: bd/system/system_ooc.xdc
