# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/system_rp_dac_0.xci
# IP: The module: 'system_rp_dac_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/fifo_axi_data_dac/fifo_axi_data_dac.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_data_dac || ORIG_REF_NAME==fifo_axi_data_dac} -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/reg_ctrl/reg_ctrl.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==reg_ctrl || ORIG_REF_NAME==reg_ctrl} -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/fifo_axi_data_dac/fifo_axi_data_dac.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data_dac || ORIG_REF_NAME==fifo_axi_data_dac} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/fifo_axi_data_dac/fifo_axi_data_dac_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data_dac || ORIG_REF_NAME==fifo_axi_data_dac} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/const.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rp_dac_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/system_rp_dac_0.xci
# IP: The module: 'system_rp_dac_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/fifo_axi_data_dac/fifo_axi_data_dac.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_data_dac || ORIG_REF_NAME==fifo_axi_data_dac} -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/reg_ctrl/reg_ctrl.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==reg_ctrl || ORIG_REF_NAME==reg_ctrl} -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/fifo_axi_data_dac/fifo_axi_data_dac.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data_dac || ORIG_REF_NAME==fifo_axi_data_dac} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/fifo_axi_data_dac/fifo_axi_data_dac_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data_dac || ORIG_REF_NAME==fifo_axi_data_dac} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_dac_0/src/const.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rp_dac_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
