# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_counter_0_0/system_rp_counter_0_0.xci
# IP: The module: 'system_rp_counter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_data/fifo_axi_data.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_req/fifo_axi_req.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_data/fifo_axi_data.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_data/fifo_axi_data_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_req/fifo_axi_req.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_req/fifo_axi_req_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_counter_0_0/system_rp_counter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rp_counter_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_counter_0_0/system_rp_counter_0_0.xci
# IP: The module: 'system_rp_counter_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_data/fifo_axi_data.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_req/fifo_axi_req.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_data/fifo_axi_data.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_data/fifo_axi_data_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_data || ORIG_REF_NAME==fifo_axi_data} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_req/fifo_axi_req.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/ip/fifo_axi_req/fifo_axi_req_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_axi_req || ORIG_REF_NAME==fifo_axi_req} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_rp_counter_0_0/system_rp_counter_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_rp_counter_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
