# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2.xci
# IP: The module: 'system_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2.xci
# IP: The module: 'system_xbar_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/pinceta/RedPitaya/RedPitaya/fpga/classic/prj/stream_app/project/redpitaya.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xbar_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
