# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/bd/system/ip/system_waveform_top_0_0/system_waveform_top_0_0.xci
# IP: The module: 'system_waveform_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# XDC: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/bd/system/ip/system_waveform_top_0_0/system_waveform_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_waveform_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/bd/system/ip/system_waveform_top_0_0/system_waveform_top_0_0.xci
# IP: The module: 'system_waveform_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_bram_ctrl_0 || ORIG_REF_NAME==axi_bram_ctrl_0} -quiet] -quiet

# XDC: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc

# XDC: /home/martin/projects/RedPitaya_SiPM/fpga/project/redpitaya.srcs/sources_1/bd/system/ip/system_waveform_top_0_0/system_waveform_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_waveform_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
